# Generated by Django 5.2.6 on 2025-09-25 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0004_alter_track_name'),
        ('trainee', '0003_trainee_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='track',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='track.track'),
        ),
    ]
