# Generated by Django 5.2.6 on 2025-09-23 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='name',
        ),
    ]
