# Generated by Django 5.2.6 on 2025-09-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0003_track_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='name',
            field=models.CharField(default='python', max_length=100),
        ),
    ]
